name: Run Python Script

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # You can choose your desired Python version

    - name: Run Python Script
      run: python ci_cd.py  # Replace 'your_script.py' with the name of your Python script

    - name: Print Result
      run: |
        echo "Result:"
        cat result.txt  # Assuming your Python script writes the result to a file named 'result.txt'
